name: tphotos
description: "A photo and video management app for TerraPhotos."
publish_to: 'none'
version: 0.2.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  encrypt: ^5.0.1
  pointycastle: ^3.9.1
  shared_preferences: ^2.3.2
  visibility_detector: ^0.4.0
  saver_gallery: ^4.0.1
  path: ^1.9.0
  path_provider: ^2.1.3
  crypto: ^3.0.3
  video_player: ^2.9.1
  fvp: ^0.35.0
  video_player_control_panel: ^1.1.3
  package_info_plus: ^9.0.0
  url_launcher: ^6.3.2
  dynamic_color: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
