name: tphotos
description: "A photo and video management app for TerraPhotos."
publish_to: 'none'
version: 0.3.2

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.2.0
  encrypt: ^5.0.1
  pointycastle: ^3.9.1
  shared_preferences: ^2.3.2
  visibility_detector: ^0.4.0
  saver_gallery: ^4.0.1
  path: ^1.9.0
  path_provider: ^2.1.3
  crypto: ^3.0.3
  media_kit: ^1.2.6
  media_kit_video: ^2.0.1
  media_kit_libs_video: ^1.0.7
  package_info_plus: ^9.0.0
  url_launcher: ^6.3.2
  dynamic_color: ^1.7.0
  chinese_font_library: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
